apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-media-spark
  template:
    metadata:
      labels:
        app: social-media-spark
    spec:
      containers:
        - name: spark
          image: social-media-spark:stable-demo
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: pipeline-runtime-config
          env:
            - name: PYSPARK_PYTHON
              value: python
            - name: PYTHONPATH
              value: /opt/social-media-analytics
            - name: RESET_CHECKPOINT_ON_START
              value: "false"
            - name: SPARK_RESOLVE_PACKAGES
              value: "false"
          command:
            - /bin/bash
            - -lc
            - |
              spark-submit /opt/social-media-analytics/spark_jobs/public_content/stream_processor.py
